title:            cusxio | Welcome
url:              http://iam.cusx.io
permalink:        pretty
highlighter:      pygments
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: 
timezone:         Australia/Perth
paginate: 5
links: 
  - name:         About
    url:          /about