title:            Uei-Shen Chan - No Label
url:              http://iam.cusx.io
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: 
timezone:         Australia/Perth
paginate: 5
links: 
  - name:         About
    url:          /about